db:
  image: mongo
  extra_hosts:
    mongo: 127.0.0.1
  ports:
    - "27017:27017"
frontend:
  image: hypfrontend
  extra_hosts:
    hypfrontend: 127.0.0.1
  ports:
    - "3000:3005"
backend:
  image: hypbackend
  extra_hosts:
    hypbackend: 127.0.0.1
  ports:
    - "3001:3001"
  links:
   - db
  environment:
    - "MONGO_URI=db"
    - "NODE_ENV=development"
admin:
  image: hypadmin
  links:
   - db
  extra_hosts:
    hypfrontend: 127.0.0.1
  ports:
    - "3002:3000"
  environment:
    - "MONGO_URI=mongodb://db:27017/dev"
